# -*- MakeFile -*-

# MACRO = substitute with this

# directories

PNP_DIR = ../

MODULES_DIR = $(PNP_DIR)/modules/

CTRL_DIR = $(MODULES_DIR)/ctrl/
DATA_DIR = $(MODULES_DIR)/data/
GAME_DIR = $(MODULES_DIR)/game/
GEN_DIR = $(MODULES_DIR)/gen/
PRNT_DIR = $(MODULES_DIR)/prnt/
SAVE_DIR = $(MODULES_DIR)/save/
UI_DIR = $(MODULES_DIR)/ui/

# dependencies


# target: dependencies
#	action

all:
	cd $(CTRL_DIR) && $(MAKE) && cd ..
	cd $(DATA_DIR) && $(MAKE) && cd ..
	cd $(GAME_DIR) && $(MAKE) && cd ..
	cd $(GEN_DIR) && $(MAKE) && cd ..
	cd $(PRNT_DIR) && $(MAKE) && cd ..
	cd $(SAVE_DIR) && $(MAKE) && cd ..
	cd $(UI_DIR) && $(MAKE) && cd ..


clean:
	cd $(CTRL_DIR) && $(MAKE) clean && cd ..
	cd $(DATA_DIR) && $(MAKE) clean && cd ..
	cd $(GAME_DIR) && $(MAKE) clean && cd ..
	cd $(GEN_DIR) && $(MAKE) clean && cd ..
	cd $(PRNT_DIR) && $(MAKE) clean && cd ..
	cd $(SAVE_DIR) && $(MAKE) clean && cd ..
	cd $(UI_DIR) && $(MAKE) clean && cd ..

################################################################################
######## End of file ###########################################################
################################################################################
######## End of file ###########################################################
################################################################################
######## End of file ###########################################################
################################################################################
