# -*- MakeFile -*-

# MACRO = substitute with this

# directories

PNP_DIR = ../

MODULES_DIR = $(PNP_DIR)/modules/

CHK_DIR = $(MODULES_DIR)/chk/
CTRL_DIR = $(MODULES_DIR)/ctrl/
DATA_DIR = $(MODULES_DIR)/data/
GAME_DIR = $(MODULES_DIR)/game/
GEN_DIR = $(MODULES_DIR)/gen/
PRN_DIR = $(MODULES_DIR)/prn/
UI_DIR = $(MODULES_DIR)/ui/

# dependencies


# target: dependencies
#	action

all:
	cd $(CHK_DIR) && $(MAKE) && cd ..
	cd $(CTRL_DIR) && $(MAKE) && cd ..
	cd $(DATA_DIR) && $(MAKE) && cd ..
	cd $(GAME_DIR) && $(MAKE) && cd ..
	cd $(GEN_DIR) && $(MAKE) && cd ..
	cd $(PRN_DIR) && $(MAKE) && cd ..
	cd $(UI_DIR) && $(MAKE) && cd ..


clean:
	cd $(CHK_DIR) && $(MAKE) clean && cd ..
	cd $(CTRL_DIR) && $(MAKE) clean && cd ..
	cd $(DATA_DIR) && $(MAKE) clean && cd ..
	cd $(GAME_DIR) && $(MAKE) clean && cd ..
	cd $(GEN_DIR) && $(MAKE) clean && cd ..
	cd $(PRN_DIR) && $(MAKE) clean && cd ..
	cd $(UI_DIR) && $(MAKE) clean && cd ..

################################################################################
######## End of file ###########################################################
################################################################################
######## End of file ###########################################################
################################################################################
######## End of file ###########################################################
################################################################################
