# -*- MakeFile -*-

# MACRO = substitute with this

# directories

ABOUT_DIR = $(MODULES_DIR)/about/
CTRL_DIR = $(MODULES_DIR)/ctrl/
GAME_DIR = $(MODULES_DIR)/game/
MENU_DIR = $(MODULES_DIR)/menu/
PLAY_DIR = $(MODULES_DIR)/player/
SAVE_DIR = $(MODULES_DIR)/save/
XYZZY_DIR = $(MODULES_DIR)/xyzzy/

export	ABOUT_DIR
export	CTRL_DIR
export	GAME_DIR
export	MENU_DIR
export	PLAY_DIR
export	SAVE_DIR
export	XYZZY_DIR

# dependencies


# target: dependencies
#	action

all:
	$(Q)cd $(ABOUT_DIR) && $(MAKE) && cd ..
	$(Q)cd $(CTRL_DIR) && $(MAKE) && cd ..
	$(Q)cd $(GAME_DIR) && $(MAKE) && cd ..
	$(Q)cd $(MENU_DIR) && $(MAKE) && cd ..
	$(Q)cd $(PLAY_DIR) && $(MAKE) && cd ..
	$(Q)cd $(SAVE_DIR) && $(MAKE) && cd ..
	$(Q)cd $(XYZZY_DIR) && $(MAKE) && cd ..


clean:
	$(Q)cd $(ABOUT_DIR) && $(MAKE) clean && cd ..
	$(Q)cd $(CTRL_DIR) && $(MAKE) clean && cd ..
	$(Q)cd $(GAME_DIR) && $(MAKE) clean && cd ..
	$(Q)cd $(MENU_DIR) && $(MAKE) clean && cd ..
	$(Q)cd $(PLAY_DIR) && $(MAKE) clean && cd ..
	$(Q)cd $(SAVE_DIR) && $(MAKE) clean && cd ..
	$(Q)cd $(XYZZY_DIR) && $(MAKE) clean && cd ..
	@echo  "Clean modules"

################################################################################
######## End of file ###########################################################
################################################################################
######## End of file ###########################################################
################################################################################
######## End of file ###########################################################
################################################################################
