# -*- MakeFile -*-

# MACRO = substitute with this

# directories

LIBALX_DIR = ./

OBJ_DIR = $(LIBALX_DIR)/obj/


# target: dependencies
#	action

all:
	cd $(OBJ_DIR) && $(MAKE) && cd ..


clean:
	cd $(OBJ_DIR) && $(MAKE) clean && cd ..
