# -*- MakeFile -*-

# MACRO = substitute with this

# directories

OBJ_DIR = $(LIBALX_DIR)/obj/


# target: dependencies
#	action

all:
	$(Q)cd $(OBJ_DIR) && $(MAKE) && cd ..


clean:
	$(Q)cd $(OBJ_DIR) && $(MAKE) clean && cd ..
	@echo  "Clean libalx"
